#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GymApp.Resource", IsApplication=true)]

namespace GymApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int iconoGymApp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int informacion = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pago = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int rutinas = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000c
			public const int Abdomen = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int Brazo = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int Cadera = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int Cintura = 2131165195;
			
			// aapt resource value: 0x7f070009
			public const int Espalda = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int IndiceDeMasaCorporal = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int Muslo = 2131165198;
			
			// aapt resource value: 0x7f070003
			public const int Nombre = 2131165187;
			
			// aapt resource value: 0x7f07000f
			public const int Pantorrilla = 2131165199;
			
			// aapt resource value: 0x7f070008
			public const int Pecho = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int Peso = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int PorcentajeDeAgua = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int PorcentajeDeGrasa = 2131165189;
			
			// aapt resource value: 0x7f070018
			public const int btnIngresar = 2131165208;
			
			// aapt resource value: 0x7f070011
			public const int button2 = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int button3 = 2131165203;
			
			// aapt resource value: 0x7f070017
			public const int espacioContraseña = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int espacioUsuario = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int imageView2 = 2131165204;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout0 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout1 = 2131165186;
			
			// aapt resource value: 0x7f070010
			public const int linearLayout2 = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int linearLayout3 = 2131165202;
			
			// aapt resource value: 0x7f070000
			public const int tabHost1 = 2131165184;
			
			// aapt resource value: 0x7f070015
			public const int textView1 = 2131165205;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Index = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Login = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int iconoGymApp = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme3 = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
